config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :recipes do
    resources :ingredients
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def create
  @recipe = Recipe.find(params[:recipe_id])
  @ingredient = @recipe.ingredients.create(ingredient_params)
  redirect_to recipe_path(@recipe)
end

def destroy
  @recipe = Article.find(params[:recipe_id])
  @comment = @recipe.comments.find(params[:id])
  @comment.destroy
  redirect_to article_path(@recipe)
end

private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
   @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :serving, :time)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: [ @recipe, @recipe.ingredients.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/ingredients/_ingredient.html.erb
    <ul>
    <%= ingredient.name %>
    <%= link_to 'Delete', [ingredient.recipe, ingredient],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondRecipeBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, local: true do |form| %>

<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :serving %><br>
    <%= form.text_area :serving %>
  </p>

  <p>
    <%= form.label :time %><br>
    <%= form.text_area :time %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Servings</th>
    <th>Time</th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.title %></td>
      <td><%= recipe.serving %></td>
      <td><%= recipe.time %></td>
      <td><%= link_to 'Show', recipe_path(recipe) %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Destroy', recipe_path(recipe),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Servings:</strong>
  <%= @recipe.serving %>
</p>
<p>
  <strong>Time:</strong>
  <%= @recipe.time %>
</p>

<h2>Ingredients</h2>
<%= render @recipe.ingredients %>
<p>

<h2>Add an ingredient:</h2>
<%= render 'ingredients/form'%>
<p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Back', recipes_path %>

app/views/welcome/index.html.erb
<h1>Recipe Book</h1>
<%= link_to 'My Recipes', controller: 'recipes' %>
<%= link_to 'New Recipe', new_recipe_path %>